/* Copyright 2025 Philippe Felix Haupt, Eric-Ramon Kreyer, Andrea Bocci, René Widera
 * SPDX-License-Identifier: Apache-2.0
 */

#include "config.h"
#include "naive_cpu.h"

#include <alpaka/alpaka.hpp>

#include <cassert>
#include <chrono>
#include <cstdio>
#include <iostream>
#include <random>
#include <vector>

using namespace alpaka;

// This kernel demonstrates the basic/unoptimized GEMM operation using a CUDA like programming model.
// This is actually an example of bad practice as the alpaka framework provides primitives to write platform
// independent HPC code. We will demonstrate these in further examples. With this kernel, we also intend to highlight
// vector indexing as many people may find it unintuitive.
struct CudaLikeSGEMM
{
    template<typename TAcc>
    ALPAKA_FN_ACC void operator()(TAcc const& acc, auto const A, auto const B, auto out, float alpha, float beta) const
    {
        // Depending on the FrameSpec given to the kernel, these functions may return multidimensional indices.
        auto threadIndexMD = acc[layer::thread].idx();
        auto blockDimensionMD = acc[layer::thread].count();
        auto blockIndexMD = acc[layer::block].idx();
        auto gridDimensionMD = acc[layer::block].count();

        using IndexType = typename ALPAKA_TYPEOF(gridDimensionMD)::index_type;

        // Global index calculation for 2D grid-stride
        IndexType const tRow = blockIndexMD.x() * blockDimensionMD.x() + threadIndexMD.x();
        IndexType const tCol = blockIndexMD.y() * blockDimensionMD.y() + threadIndexMD.y();

        // Nested loop for calculating SGEMM for mxn and nxk matrices
        for(IndexType row = tRow; row < out.getExtents().y(); row += blockDimensionMD.x() * gridDimensionMD.x())
        {
            for(IndexType col = tCol; col < out.getExtents().x(); col += blockDimensionMD.y() * gridDimensionMD.y())
            {
                float tmp = 0.;
                for(IndexType k = 0; k < A.getExtents().x(); k++)
                {
                    // 2D buffers can be accessed via a 2D Vector
                    // Notice how 'row' which stems from our x index is used as the second index in our buffers
                    // We defined/constrained our buffers so x corresponds to the row and y to the column
                    // In alpaka multidimensional vectors 'x' is defined as the highest/rightmost index
                    // The rightmost index is also the 'fastest' in autogenerated loops (more on that in later
                    // examples) or accesses sequential memory Keeping this in mind is imperative for optimizing memory
                    // access patterns!
                    tmp += A[Vec2D{row, k}] * B[Vec2D{k, col}];
                }
                out[Vec2D{row, col}] = alpha * tmp + beta * out[Vec2D{row, col}];
            }
        }
    }
};

int testCudaLikeKernel(onHost::concepts::Device auto device, auto computeExec)
{
    // random number generator with a gaussian distribution
    std::random_device rd{};
    std::default_random_engine rand{rd()};
    std::normal_distribution<float> dist{0.f, 1.f};

    // tolerance
    constexpr float epsilon = 1e-4;

    // 2-dimensional and linearised buffer size
    constexpr Vec2D A_size = {256, 1024};
    constexpr Vec2D B_size = {1024, 256};
    constexpr Vec2D C_size = {A_size.y(), B_size.x()};
    constexpr size_t flopCount = static_cast<size_t>(A_size.x()) * C_size.product() * 2u + 2u * C_size.product();
    static_assert(A_size.x() == B_size.y());
    static_assert(A_size.y() == C_size.y());
    static_assert(B_size.x() == C_size.x());
    float alpha = 1.0;
    float beta = 0.5;

    // allocate input and output host buffers in pinned memory accessible by the Platform devices
    auto A_h = onHost::allocHost<float>(A_size);
    auto B_h = onHost::allocHost<float>(B_size);
    auto C_h = onHost::allocHost<float>(C_size);

    // fill the input buffers with random data, and the output buffer with zeros
    for(uint32_t j = 0; j < A_size.y(); ++j)
        for(uint32_t i = 0; i < A_size.x(); ++i)
            A_h[Vec2D{j, i}] = dist(rand);
    for(uint32_t j = 0; j < B_size.y(); ++j)
        for(uint32_t i = 0; i < B_size.x(); ++i)
            B_h[Vec2D{j, i}] = dist(rand);
    for(uint32_t j = 0; j < C_size.y(); ++j)
        for(uint32_t i = 0; i < C_size.x(); ++i)
            C_h[Vec2D{j, i}] = 0.;

    // run the test the given device
    onHost::Queue queue = device.makeQueue();

    // allocate input and output buffers on the device
    auto A_d = onHost::allocLike(device, A_h);
    auto B_d = onHost::allocLike(device, B_h);
    auto C_d = onHost::allocLike(device, C_h);

    // copy the input data to the device; the size is known from the buffer objects
    onHost::memcpy(queue, A_d, A_h);
    onHost::memcpy(queue, B_d, B_h);

    // fill the output buffer with zeros; the size is known from the buffer objects
    onHost::memset(queue, C_d, 0x00);

    auto threadSpec = onHost::ThreadSpec{divExZero(C_size, Vec2D{16, 16}), Vec2D{16, 16}};

    // launch the 1-dimensional kernel with scalar size
    if constexpr(isSeqExecutor(computeExec))
    {
        std::cout << "Sequential Executor detected!" << std::endl;
        threadSpec = onHost::ThreadSpec{Vec2D{16, 16}, Vec2D{1, 1}};
    }

    std::cout << "Testing CudaLikeSGEMM with scalar indices with a grid of " << threadSpec.getNumBlocks() << ","
              << threadSpec.getNumThreads() << "\n";

    onHost::wait(queue);
    auto const beginT = std::chrono::high_resolution_clock::now();
    queue.enqueue(computeExec, threadSpec, CudaLikeSGEMM{}, A_d, B_d, C_d, alpha, beta);
    onHost::wait(queue);
    auto const endT = std::chrono::high_resolution_clock::now();

    double duration = std::chrono::duration<double>(endT - beginT).count();
    std::cout << "Time for kernel execution: " << duration << " s" << std::endl;
    std::cout << "  - flop count : " << flopCount << std::endl;
    std::cout << "  - performance: " << static_cast<double>(flopCount) / 1.e12 / duration << " tflop/s" << std::endl;

    // copy the results from the device to the host
    onHost::memcpy(queue, C_h, C_d);

    // check the results
    auto cpu_out = onHost::allocHostLike(C_h);
    onHost::memset(queue, cpu_out, 0x00);

    // wait for all the operations to complete
    onHost::wait(queue);

    // Perform a naive CPU matrix multiplication to compare the results
    naive_matrix_mult(A_h, B_h, cpu_out, alpha, beta);

    bool mismatch = false;
    for(uint32_t i = 0; i < C_size.product(); ++i)
    {
        auto lIdx = mapToND(C_size, i);
        if(!(std::abs(C_h[lIdx] - cpu_out[lIdx]) < epsilon))
        {
            std::cout << "MISMATCH at " << lIdx << " kernel=" << C_h[lIdx] << " cpu=" << cpu_out[lIdx] << std::endl;
            mismatch = true;
        }
        assert(std::abs(C_h[lIdx] - cpu_out[lIdx]) < epsilon);
    }

    if(!mismatch)
        std::cout << "success\n";

    return mismatch ? EXIT_FAILURE : EXIT_SUCCESS;
}

int example(auto const cfg)
{
    auto deviceSpec = cfg[object::deviceSpec];
    auto computeExec = cfg[object::exec];

    std::cout << "Using alpaka accelerator: " << onHost::demangledName(computeExec) << " for "
              << deviceSpec.getApi().getName() << " " << deviceSpec.getDeviceKind().getName() << std::endl;

    // Select a device
    auto devSelector = onHost::makeDeviceSelector(deviceSpec);
    if(!devSelector.isAvailable())
    {
        std::cout << "No device available for " << deviceSpec.getName() << std::endl;
        return EXIT_SUCCESS;
    }

    // use the first device
    onHost::Device device = devSelector.makeDevice(0);
    std::cout << "Device: " << onHost::getName(device) << "\n\n";

    return testCudaLikeKernel(device, computeExec);
}

auto main() -> int
{
    // Execute the example once for each enabled API and executor.
    // Execute the example once for each enabled API and executor.
    return onHost::executeForEachIfHasDevice(
        [=](auto const& cfg) { return example(cfg); },
        onHost::allBackends(onHost::enabledApis, exec::enabledExecutors));
}
